FROM golang:1.15-alpine3.12

# USERNAME == GROUP for now
ARG USERNAME=odapps

# Default vscode UID/GID (can be overriden with args)
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN addgroup -g $USER_GID $USERNAME \
    && adduser -D -u $USER_UID -G $USERNAME $USERNAME

COPY . /go/src
WORKDIR /go/src

# Add development dependencies
RUN go get -v golang.org/x/tools/gopls@latest \
    && go mod vendor

USER $USERNAME